global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['host.docker.internal:9121']