apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: ${LOKI_URL}
    editable: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    sslMode: disable
    editable: true
    jsonData:
      postgresVersion: ${POSTGRES_VERSION:-15}
      timescaledb: false